In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

import warnings
warnings.filterwarnings("ignore")

In [2]:
# Read csv file
df = pd.read_csv('/kaggle/input/iris-flower-dataset/IRIS.csv')
df

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

### Exploratory data analysis

In [3]:
df.tail()

     sepal_length  sepal_width  petal_length  petal_width         species
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

In [4]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [6]:
df.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [7]:
# df.isnull()
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

### Calculate unique values

In [8]:
df['species'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

### Converting categorical data into numerical data

In [9]:
df['species'].replace({'Iris-setosa':1,'Iris-versicolor':2,'Iris-virginica':3}, inplace=True)
df

     sepal_length  sepal_width  petal_length  petal_width  species
0             5.1          3.5           1.4          0.2        1
1             4.9          3.0           1.4          0.2        1
2             4.7          3.2           1.3          0.2        1
3             4.6          3.1           1.5          0.2        1
4             5.0          3.6           1.4          0.2        1
..            ...          ...           ...          ...      ...
145           6.7          3.0           5.2          2.3        3
146           6.3          2.5           5.0          1.9        3
147           6.5          3.0           5.2          2.0        3
148           6.2          3.4           5.4          2.3        3
149           5.9          3.0           5.1          1.8        3

[150 rows x 5 columns]

### Splitting data into training and test dataset

In [10]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split (df[['sepal_length','sepal_width','petal_length','petal_width']], df['species'], test_size=0.2)

In [11]:
print("Xtrain lenght: ", len(x_train))
print("Xtest lenght: ", len(x_test))
print("ytrain lenght: ", len(y_train))
print("ytest lenght: ", len(y_test))

Xtrain lenght:  120
Xtest lenght:  30
ytrain lenght:  120
ytest lenght:  30

In [12]:
# Check the shape of xtrain and xtest -> must (a, 1)
print("Xtrain shape: ",x_train.shape)
print("Xtest shape: ", x_test.shape)
print("ytrain shape: ",y_train.shape)
print("ytest shape: ", y_test.shape)

Xtrain shape:  (120, 4)
Xtest shape:  (30, 4)
ytrain shape:  (120,)
ytest shape:  (30,)

### Building Logistic Regression Model

In [13]:
from sklearn.linear_model import LogisticRegression

# Creating object of Logistic Regression
lr = LogisticRegression()

###  Training dataset

In [14]:
lr.fit(x_train, y_train)

LogisticRegression()

### Predicting values

In [15]:
lr.predict(x_test)

lr.predict([[8.1,4.8,2.5,1.3]])

y_pred = lr.predict(x_test)

### Checking accuracy

In [16]:
lr.score(x_test, y_test)

0.9666666666666667

In [17]:
from sklearn.metrics import accuracy_score

acc2 = accuracy_score(y_test, y_pred)
acc2

0.9666666666666667

In [18]:
acc3 = accuracy_score(y_test, y_pred)
acc3

0.9666666666666667